### ISSUE TITLE
feat: network

### ISSUE THREAD

**Issue by Serein207** [NJUPT-SAST-Cpp/sast-music#6]
文件目录，文件名
Infrastructure/Network/NetworkClient.h
Infrastructure/Network/NetworkClient.cpp

**Comment by ArcticLampyrid** [comment]
something to discuss：
- 是否使用薛老师的json序列化工具
- 异步机制
- - Callback Hell 模式
- - What the fucking `QFuture`.
- - 信号槽
- 是否容许引入其它库 (eg. boost/openssl/mbedtls/...)
- - 通过 VCPKG？

**Comment by Serein207** [comment]
怎么方便怎么来吧，看你了
QFuture的规范用法会不会是 函数返回QPromise，然后用QFuture接收返回结果呢（不是很确定，去查一下文档吧）

**Comment by ArcticLampyrid** [comment]
Current Design:
- 回调地狱模式（至少它没坑
- mbedtls as submodule
